"""create initial study schema

Revision ID: 2993397fa840
Revises: 
Create Date: 2026-06-23 20:34:49.313577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2993397fa840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_code', sa.String(length=64), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_code', name='uq_participants_participant_code')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_scenarios_version_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uq_scenarios_slug_version')
    )
    op.create_index('ix_scenarios_category', 'scenarios', ['category'], unique=False)
    op.create_index('ix_scenarios_is_active', 'scenarios', ['is_active'], unique=False)
    op.create_table('scenario_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_scenario_options_display_order_nonnegative'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name='fk_scenario_options_scenario_id_scenarios', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'code', name='uq_scenario_options_scenario_code'),
    sa.UniqueConstraint('scenario_id', 'display_order', name='uq_scenario_options_scenario_display_order'),
    sa.UniqueConstraint('scenario_id', 'id', name='uq_scenario_options_scenario_id_id')
    )
    op.create_index('ix_scenario_options_scenario_id', 'scenario_options', ['scenario_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'started'"), nullable=False),
    sa.Column('randomization_seed', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('started', 'completed', 'abandoned')", name='ck_study_sessions_status'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='ck_study_sessions_completed_after_started'),
    sa.CheckConstraint('randomization_seed >= 0', name='ck_study_sessions_randomization_seed_nonnegative'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name='fk_study_sessions_participant_id_participants', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_sessions_participant_id', 'study_sessions', ['participant_id'], unique=False)
    op.create_index('ix_study_sessions_status', 'study_sessions', ['status'], unique=False)
    op.create_table('human_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='ck_human_responses_confidence_range'),
    sa.CheckConstraint('response_time_ms >= 0', name='ck_human_responses_response_time_nonnegative'),
    sa.ForeignKeyConstraint(['scenario_id', 'selected_option_id'], ['scenario_options.scenario_id', 'scenario_options.id'], name='fk_human_responses_scenario_option', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name='fk_human_responses_scenario_id_scenarios', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name='fk_human_responses_session_id_study_sessions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'scenario_id', name='uq_human_responses_session_scenario')
    )
    op.create_index('ix_human_responses_scenario_id', 'human_responses', ['scenario_id'], unique=False)
    op.create_index('ix_human_responses_selected_option_id', 'human_responses', ['selected_option_id'], unique=False)
    op.create_index('ix_human_responses_session_id', 'human_responses', ['session_id'], unique=False)
    op.create_table('machine_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_machine_predictions_confidence_range'),
    sa.ForeignKeyConstraint(['scenario_id', 'selected_option_id'], ['scenario_options.scenario_id', 'scenario_options.id'], name='fk_machine_predictions_scenario_option', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name='fk_machine_predictions_scenario_id_scenarios', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'model_name', 'model_version', name='uq_machine_predictions_scenario_model_version')
    )
    op.create_index('ix_machine_predictions_scenario_id', 'machine_predictions', ['scenario_id'], unique=False)
    op.create_index('ix_machine_predictions_selected_option_id', 'machine_predictions', ['selected_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machine_predictions_selected_option_id', table_name='machine_predictions')
    op.drop_index('ix_machine_predictions_scenario_id', table_name='machine_predictions')
    op.drop_table('machine_predictions')
    op.drop_index('ix_human_responses_session_id', table_name='human_responses')
    op.drop_index('ix_human_responses_selected_option_id', table_name='human_responses')
    op.drop_index('ix_human_responses_scenario_id', table_name='human_responses')
    op.drop_table('human_responses')
    op.drop_index('ix_study_sessions_status', table_name='study_sessions')
    op.drop_index('ix_study_sessions_participant_id', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('ix_scenario_options_scenario_id', table_name='scenario_options')
    op.drop_table('scenario_options')
    op.drop_index('ix_scenarios_is_active', table_name='scenarios')
    op.drop_index('ix_scenarios_category', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('participants')
    # ### end Alembic commands ###
